FROM python:3.7
COPY db* /app/
COPY requirements.txt /app/
WORKDIR /app
RUN pip3 install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/
EXPOSE 30855
CMD ["python", "db-server.py"]
