FROM openjdk:8-jre-alpine
ADD logflashdb.jar /opt

COPY dbmanager-entrypoint.sh /
COPY wait-for.sh /
Run chmod 775 /dbmanager-entrypoint.sh
Run chmod 775 /wait-for.sh

ENTRYPOINT ["/dbmanager-entrypoint.sh"]
CMD ["--help"]